services:
  backend:
    container_name: backend-container
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: meterAI
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
